policy:
  - template: [report-a-bug.yml]
    section:
      - id: [minecraftVersion]
        block-list: [other]
        label:
          - name: Minecraft 1.21.4
            keys: ['1.21.4']
          - name: Minecraft 1.21.1 
            keys: ['1.21.1 (LTS)']
          - name: Minecraft 1.20.1
            keys: ['1.20.1 (LTS)']
          - name: EOL
            keys: ['Other (specify below)']
      - id: [modLoader]
        label:
          - name: NeoForge
            keys: ['NeoForge']
          - name: Fabric
            keys: ['Fabric']
          - name: 'Forge'
            keys: ['Forge']